language: ruby
rvm:
  - 2.3.0

services:
  - mysql

before_instal:
  - mysql -e 'CREATE DATABASE packinglist_test;'

before_script:
  - cp config/database.travis.yml config/database.yml

cache: bundle